apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jwt-server-v1
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: jwt-server-v1
    spec:
      containers:
      - name: jwt-server-container
        image: mjzhang88/oauth2-jwt-server
        volumeMounts:
        ports:
        - containerPort: 9002

